#!/bin/bash
# regdump -t SYSTEM > SYSTEM.dump && usbinfo SYSTEM.dump
# https://github.com/adoxa/regdump


exit_error() { [ "${2:-}" ] && echo $2 > /dev/stderr; exit ${1:-1}; }
get_value() { read stdin; echo ${stdin##* = }; }


registry=${1:?$'\r'SYSTEM registry dump needed$'\033[K'}
[ -s "$registry" ] || exit_error 1 "Non-existent or empty registry dump"


# Current ControlSet
read Current _ < <( grep -m1 '/Select/Current ' $registry | get_value )
[ "$Current" ] && [ $((Current)) -gt 0 ] || Current=1
Current=000$((Current))
ControlSet=ControlSet${Current: -3}


# node reduction
registry=$( mktemp )
registry=${registry:?$'\r'Error with temporay file$'\033[K'}
trap "rm -f $registry" EXIT
egrep '^\[.+/('$ControlSet'/Enum|MountedDevices)/.+ = .+' "$1" > $registry
[ -s $registry ] || exit_error 1 "Searched nodes not found"
# encoding correction (fr)
sed -i -e 's/<E0>/à/g' -e 's/<E9>/é/g' $registry


# USB storage
while read UsbStorage
do

Serial=${UsbStorage##*/}

FirstTime=$( egrep "/$Serial/|#$Serial#" $registry | sort | head -1 )
FirstTime=${FirstTime:1:19}

DeviceDesc=$( grep -m1 "$UsbStorage/DeviceDesc" $registry )
LastTime=${DeviceDesc:1:19}
DeviceDesc=${DeviceDesc##* = }
DeviceDesc=${DeviceDesc##*;}

FriendlyName=$( grep -m1 "$UsbStorage/FriendlyName" $registry | get_value )

DosDevice=$( grep "/MountedDevices/" $registry | grep "$Serial" | grep -om1 'DosDevices\\.:')
DosDevice=${DosDevice: -2}

UsbStorage=${UsbStorage%/*}
UsbStorage=${UsbStorage##*/}
UsbStorage=${UsbStorage%&Rev_*}
UsbStorage=${UsbStorage//&/ }
UsbStorage=${UsbStorage//Ven_/}
UsbStorage=${UsbStorage//Prod_/}

echo $LastTime\
$'\t'$UsbStorage\
$'\t'$Serial\
$'\t'$FirstTime\
$'\t'$DeviceDesc\
$'\t'$FriendlyName\
$'\t'$DosDevice

done < <( egrep -o "$ControlSet/Enum/USBSTOR/[^/]+/[^/]+" $registry | sort -u )


# USB Vid Pid
while read VidPid
do

Serial=${VidPid##*/}

FirstTime=$( egrep "/$Serial/|#$Serial#" $registry | sort | head -1 )
FirstTime=${FirstTime:1:19}

DeviceDesc=$( grep -m1 "$VidPid/DeviceDesc" $registry )
LastTime=${DeviceDesc:1:19}
DeviceDesc=${DeviceDesc##* = }
DeviceDesc=${DeviceDesc##*;}

FriendlyName=$( grep -m1 "$VidPid/FriendlyName" $registry | get_value )

VidPid=${VidPid%/*}
VidPid=${VidPid##*/}
VidPid=${VidPid%&MI_*}
VidPid=${VidPid//&/ }
VidPid=${VidPid/VID_/VId }
VidPid=${VidPid/PID_/PId }

echo $LastTime\
$'\t'$VidPid\
$'\t'$Serial\
$'\t'$FirstTime\
$'\t'$DeviceDesc\
$'\t'$FriendlyName\

done < <( egrep -o "$ControlSet/Enum/USB/VID_[^/]+/[^/]+" $registry | sort -u )

